### ISSUE TITLE
Doesn't work with Unity 2018.3.0f2

### ISSUE THREAD

**Issue by tusharsankhala** [Looooong/Unity-SRP-VXGI#1]
Hi,
Tried with Unity 2018.3.0f2, no effect of VXGI, that i can see.
Hope you could help.

Thanks,
Tushar
![novxgi](https://user-images.githubusercontent.com/7521113/53817218-fd58c200-3f8a-11e9-844e-8f879b137077.JPG)

**Comment by Looooong** [comment]
Can you show the output of console?

**Comment by Looooong** [comment]
Looks like upgrading to any verions of Unity forces re-importing the whole project. In my experience, this process usually breaks the currently used render pipeline asset (located in `Assets/Profiles/VXGIRenderPipeline.asset`), and thus Unity switch back to use the default render pipeline.

This is not an actual problem though. All you have to do is to re-create a new render pipeline asset by going to the Create menu: `Create/Rendering/VXGI Render Pipeline Asset`. Then go to `Edit/Project Settings/Graphics`. Under the inspector, drop the newly created asset into `Scriptable Render Pipeline Settings`. It looks like this:

![screenshot from 2019-03-06 16-48-53](https://user-images.githubusercontent.com/8206622/53872047-ecae5780-402f-11e9-8115-c11688a96144.png)

**Comment by tusharsankhala** [comment]
Hi,

Thanks for the reply.
I followed the same steps that you have mentioned, but still no output in unity.
I am attaching the screenshot of asset and console.

![new_vxgiasset](https://user-images.githubusercontent.com/7521113/53893516-5b9da780-4054-11e9-98af-d5dbbe5005c3.JPG)
![consolecapture](https://user-images.githubusercontent.com/7521113/53893517-5c363e00-4054-11e9-9e24-b71693926130.JPG)

**Comment by Looooong** [comment]
What kind of OS are you working on? And what kind of graphics card and graphics API you are using?

**Comment by tusharsankhala** [comment]
Working on windows 10 64 bit
GPU: Nvidia 660ti

**Comment by Looooong** [comment]
Strange. I imported this project onto Unity 2018.3.6f1 and it works fine.

**Comment by Looooong** [comment]
I think that the voxel lighting environment is not created. You can click on Camera object, under the `VXGI` component, change `Resolution` to a lower value like Low or Medium. I doubt that your GPU cannot create high resolution voxel texture.

**Comment by tusharsankhala** [comment]
I tried with Low res as well but issue is still there can't see VXGI, might be due to my graphics card. :(
But anyways thanks for the help, hoping to see new updates on this repo, will surely try again after upgrading my PC.

**Comment by Looooong** [comment]
I see that the GTX 660ti can have 2GB to 3GB of RAM. The highest resolution only consumes around 800MB of RAM. I wanna know if your card is supporting 16-bit floating-point 3D render texture format. [Here is the document for this format](https://docs.unity3d.com/ScriptReference/RenderTextureFormat.ARGBHalf.html).

As stated in the document, you can check `SystemInfo.SupportsRenderTextureFormat(RenderTextureFormat.ARGBHalf)`. If it returns false, your card doesn't support this format. You can modify the source code to use other texture format, such as 8-bit floating-point.

**Comment by Looooong** [comment]
You can also send me [editor log file](https://docs.unity3d.com/Manual/LogFiles.html) after opening the project. I will inspect it later.

**Comment by jeske** [comment]
FYI - I was able to get this SRP-VXGI working today in Unity 2018.3.6f1 by following the [video tutorial](https://www.youtube.com/watch?v=nACG_mtSUDo&feature=youtu.be).  

The video tutorial is just missing a couple steps: 

1) go into Window->Packages, clicking "+", then "Add package from disk..." and navigating to the Unity-SRP-VXGI/package.json file
~~2) go into Project Settings -> Player -> Other, and change the Color Space to Linear~~

After that I think all the steps are in the video.

**Comment by Looooong** [comment]
@jeske ~~I intentionally used Gamma Color space because it looks better with high intensity light.~~ Also, I have just reorganized the project yesterday, so importing the package is different than before that.

**Comment by jeske** [comment]
Ahh... I thought I read somewhere that it needed Linear color space. That must have been my mistake. 

I'm pretty impressed with the results on my small tests. Of course there are issues, but it's a great starting point. Thanks so much for open-sourcing this!

**Comment by Looooong** [comment]
@jeske Maybe you are right about that we should pick linear color space because of calculation accuracy. I chose gamma color space a year ago and now I don't quite sure why I made that decision.

AFAIK, Linear color space pipeline removes gamma correction from input colors and textures and, later on, add gamma correction the output frame buffer. With HDR camera, very bright light will be clamped to white. ~~I think this is why I used gamma color space just to display high intensity light more nicely.~~

To use linear color space with HDR, we will need tonemapping to be able to display very bright pixel. However, the render pipeline doesn't work with post-processing stack so I cannot use its tonemapping.

I will probably open 2 issues:
+ Revisit the color space and check if color space conversion within this render pipeline is correct.
+ Make the render pipeline work with the post-processing stack or implement tonemapping on my own. I would prefer the former solution, because the later is kinda re-inventing the wheel.

**Comment by Looooong** [comment]
@jeske

> I intentionally used Gamma Color space because it looks better with high intensity light.

I was mistaken for this incorrect statement. Actually, I did use Linear color space, so you are right about this. The decision was based on [SEGI User Guide](https://github.com/sonicether/SEGI/blob/master/User%20Guide.pdf)
