### ISSUE TITLE
PostProcessingV2 not working on VXGI

### ISSUE THREAD

**Issue by Wenzy--** [Looooong/Unity-SRP-VXGI#18]
Hi,Looooong,I found PostProessingV2 not working on VXGI.
Usually,i follow this steps can make it work.

1.Download postProcessingV2 package,(I have tried 2.1.7 and 2.0.17)
2.Add two scripts: Post Process Layer and Post Process Volume in the main Camera.
3. Set the camera layer into "Postprocessing"
4.Create a Post-Processing profile in the Assets file and assign it to the Camera's Post Process Volume component's Profile

Then,in the  Post Process Volume component ,click the is Global and add different effect on it will see the PostProcess effect.Like Vignette or sth else.

But in VXGI is not successful ,did I miss any steps?

**Comment by Looooong** [comment]
Well, I didn't implement VXGI to be compatible with Post Processing. ~~The same thing happens to ProBuilder.~~ Because SRP allows us to customize the render pipeline, it is possible to break the compatibility with other tools. And sadly, I don't know how to incorporate VXGI with other tools and library.

**Comment by Wenzy--** [comment]
Thanks.I would love to make it compatible if I can.Unfortunately I don't know a lot about shader. I saw SEGI can support postprocessing.(Besides this one,i think VXGI  is better than SEGI in many aspects)Is there any easy way  I can modify for a test?Like last time u told me about how to add the ambient value.Maybe there's not that easy as I thought.

**Comment by Looooong** [comment]
SEGI can do that because it doesn't mess with the render pipeline. The library add hooks to render pipeline and apply additional image effect to the final render result (imagine painting on an existing image).

**Comment by Looooong** [comment]
I'm adding support for post-processing at #20 . You can check that branch out and test if it's working.

**Comment by Wenzy--** [comment]
![](https://i.imgur.com/4S3q4og.png)
Thanks,Looooong.That works very well!I have tested the Bloom and Vignette.

**Comment by Looooong** [comment]
Good to know that it works for you. I'm afraid that any effect relying on screen-space depth, normal or motion vector doesn't work, yet.

**Comment by Wenzy--** [comment]
I will do more tests later. Do u have twitter account?I want to recommend this addons when I release some experimental project based on VXGI.If there's not I will just post the GitHub link directly

**Comment by Looooong** [comment]
I do have a Twitter account, but I seldomly use it. You can just refer to the Github Repo directly.

**Comment by Looooong** [comment]
I have merged this feature onto the master branch. Future development will enable more effects on the post-processing stack.
