### ISSUE TITLE
NormalMap and HeightMap assign not working

### ISSUE THREAD

**Issue by Wenzy--** [Looooong/Unity-SRP-VXGI#21]
Hi,Looooong.I have downloaded this texture and try to recreate the material in VXGI.  https://cc0textures.com/view.php?tex=Tiles20

_col.jpg assign to Abedo
_rgh assign to Metallic
_nrm.jpg assign to NormalMap
_disp assign to HeightMap

That works well in standard3d mode.

![](https://i.imgur.com/zxckLQF.png)

But in VXGI.Only the abedo and metallic works well.

The normal map in some aspects can work.But I find I can't adjust the intensity value next to the "NormaMap".I can only go to the texture import settings to set the Bumpiness and press the apply to effect the normalMap.

And the height map  doesn't have any effect apply to the material.Though I have already twisted the value.

**Comment by Looooong** [comment]
Height Map or Parallax Map are not implemented yet. That's why it isn't working. I will implement everything to mimic the Unity built-in Standard Shader in the near future.

**Comment by Looooong** [comment]
You should check #24 to see if bump scale and parallax map is enabled.

**Comment by Wenzy--** [comment]
I have checked it.That works very well now!By the way.Is it possible to increase the HeightMap 's intensity?The value is next to the HeightMap in inspector.I find the max value is 0.08?

**Comment by Looooong** [comment]
I suppose it is the limit imposed by Unity.

**Comment by Looooong** [comment]
You should switch your materials to the new shaders: `VXGI/Standard` and `VXGI/Standard (Specular setup)`, instead of the old one.

**Comment by Looooong** [comment]
I have merged this into master branch.
