### ISSUE TITLE
How to hide the emissive object but remain the lighting effect?

### ISSUE THREAD

**Issue by Wenzy--** [Looooong/Unity-SRP-VXGI#22]
Hi,Looooog.I am not sure is there any way I can hide the emissive object,and at the same time ,it can keep illuminate the object around it.Sometime this can help to do some environmental lighting

![](https://i.imgur.com/weK4yNU.png)

**Comment by Looooong** [comment]
You can set the object on a separate layer, then remove that layer from the culling mask of the main camera.

**Comment by Wenzy--** [comment]
thanks,that works
