### ISSUE TITLE
Depth of field in PostProcess has some display bug

### ISSUE THREAD

**Issue by Wenzy--** [Looooong/Unity-SRP-VXGI#25]
It seems  the "blur layer' is inverse? I have also tested other object like cube,still meet the same problem. The testing is  in the branch " Switch to built-in GBuffer generator "
![](https://i.imgur.com/MsRRkzu.png)

**Comment by Looooong** [comment]
Looks like PostProcess result is flipped. Are you using DirectX or OpenGL?

**Comment by Looooong** [comment]
I need more information. Attach the Post Process Debug script onto the main Camera, change the Overlay field to Depth and Normals, then take picures of both overlay mode.

**Comment by Looooong** [comment]
I have fixed the issue, you can test it on the latest commit.

**Comment by Looooong** [comment]
The bug has been fixed.
