### ISSUE TITLE
Is it possible to set the VXGI's resolution?

### ISSUE THREAD

**Issue by Wenzy--** [Looooong/Unity-SRP-VXGI#29]
Hello.Looooong.Is it possible to custom the resolution in VXGI? Where can i modify? I know the XYZ axizs use the same resolution like a cube.But in some situation.If there's a very long object like 8 * 1 * 1 i want to render on the screen. Then there is a lot of space is useless.

![](https://i.imgur.com/4Jurfjl.png)

**Comment by Looooong** [comment]
I'm afraid this is one of the limitation of this lighting system. The voxel resolution affects the mipmap resolution as well. And I cannot think of a way to change the shape of the voxel boundary without changing the underlying voxel data presentation.

**Comment by Wenzy--** [comment]
But if i don't change the boundary.I just ban some space then i don't use that to calculate the lighting.Is it possible to improve the performance (Just my assumption)

**Comment by Wenzy--** [comment]
I found i can go to the 

public enum Resolution { Low = 33, Medium = 65, High = 129, VeryHigh = 257 }

to adjust the whole voxel's resolution.If i can ban some space base on that.then i can acheive a similar result

**Comment by Looooong** [comment]
I am against modify `Resolution` enum, as it is calculated to fit in with the mipmap generator, where each mipmap level resolution is `2^n + 1`.
