### ISSUE TITLE
improve README - which unity version? is this usable today, or tech demo?

### ISSUE THREAD

**Issue by jeske** [Looooong/Unity-SRP-VXGI#3]
This is a really promising project... 

it would be very helpful if the README said something about the state of the project...

Which Unity versions is it compatible with?

Is it usable today, or a tech demo?

What are the limitations? (issue #1 talks about it possibly not working on some GPUs)

**Comment by Looooong** [comment]
Thanks for the questions. Sure that I will improve the README later. Currently, I have to reorganize the project before writing documents and stuff.

**Comment by Looooong** [comment]
I have added requirements and screenshot to README.md. Further documentation is coming soon.

**Comment by jeske** [comment]
Excellent, thanks! If you are interested in financial funding to support work on this for Unity 2019 and Xenko, please email me at  davidj .. at .. gmail.com

**Comment by Looooong** [comment]
Thanks for the offer. I will consider it.
