### ISSUE TITLE
Particle system functionality

### ISSUE THREAD

**Issue by daalta** [Looooong/Unity-SRP-VXGI#51]
I'm having some issues with particle systems. They either seem to not render at all, or render through all geometry.

Here's a video:
![PaleForcefulHind-size_restricted](https://user-images.githubusercontent.com/9169275/81294011-89261c80-906e-11ea-9604-f92904e15992.gif)

Do yo have a guide on how to use particle systems? Or is this a bug?

I'd appreciate your help. 👋

**Comment by Looooong** [comment]
What shader does the particle material use? You should check that the particle material use `VXGI/Particles/Standard Unlit` shader. Then, make sure that the Albedo texture contains correct alpha value for transparency. You can also post an image so I can look for myself.

**Comment by Looooong** [comment]
So, I have recently added this standard particle shader with minimal support. For now, you can use `Additive` rendering mode for these particles. I will look into supporting other rendering mode as well in the future.

**Comment by daalta** [comment]
Thanks for the reply @Looooong !
> What shader does the particle material use? You should check that the particle material use VXGI/Particles/Standard Unlit shader. 

I've been using `VXGI/Particles/Standard Unlit`, you should be able to see it in the video.

>  Then, make sure that the Albedo texture contains correct alpha value for transparency.

I've been using the built-in `Default-Particle`, but I also tried opaque textures which don't need alpha. They have the same issues.

> So, I have recently added this standard particle shader with minimal support. For now, you can use Additive rendering mode for these particles. I will look into supporting other rendering mode as well in the future.

That would be great. My particle systems always show up through walls - am I doing something wrong, or is this 'intended'? 😅

**Comment by Looooong** [comment]
> That would be great. My particle systems always show up through walls - am I doing something wrong, or is this 'intended'?

Now that you say it, I realized that I forgot to set depth texture when rendering forward transparent pass (which includes particles). That's why the particles are always drawn on the screen. I'll fix it now.

**Comment by Looooong** [comment]
I have fixed the bug in #52. You can pull the newest code for the fix.

**Comment by daalta** [comment]
@Looooong Wow, thanks! That was quick. I'll try it as soon as I can.

**Comment by daalta** [comment]
Works like a charm now, good job!
